### ISSUE TITLE
Support all GitVersion variables

### ISSUE THREAD

**Issue by tobiasdiez** [GitTools/use-gitversion#6]
Currently, only three of the [GitVersion variables](https://gitversion.readthedocs.io/en/stable/more-info/variables/) are supported. It would be nice if all of them would be accessible via `${{ steps.gitversion.outputs.VARIABLE }}"`

**Comment by arturcic** [comment]
@tobiasdiez a PR If possible is very welcomed!

**Comment by tobiasdiez** [comment]
I don't have any experience with github actions, sorry.

**Comment by gep13** [comment]
@tobiasdiez currently, the three variables are output here:

https://github.com/GitTools/use-gitversion/blob/6a5567e664577400fdfd9944f043224cc04c36d1/src/main.ts#L67-L69

And the interface for all the other properties are already defined:

https://github.com/GitTools/use-gitversion/blob/6a5567e664577400fdfd9944f043224cc04c36d1/src/interfaces.ts#L60-L90

So I "think" it should be as simple as adding the additional `buildAgent.setOutput` calls.  And also, to update the docs here:

https://github.com/GitTools/use-gitversion/blob/a445d19ad939a71095166c55df6eaae62808e033/execute/action.yml#L33-L38

**Comment by arturcic** [comment]
@gep13 that is correct

**Comment by tobiasdiez** [comment]
Thanks a lot!

**Comment by arturcic** [comment]
I'll publish a new version v0.2.1 that you can start using

**Comment by arturcic** [comment]
done
